### ISSUE TITLE
Add compatibility for Zombienet to collator bin

### ISSUE THREAD

**Issue by islami00** [chocolatenetwork/chocolate-parachain#4]
Follows from #3 

## Goal

To use Zombienet to start a local testnet. 

> Main issue is being compatible with the adder-collator . The target provider is native.

## Todos

We need the following for the bin to be compatible with the `adder-collator`

- [ ] Add `parachain-id` cli option from Polkadot `adder-collator`

**Comment by islami00** [comment]
Struct opt: https://www.youtube.com/watch?v=IVifko1fqjw

**Comment by islami00** [comment]
A close alternative could be #11

**Comment by pepoviola** [comment]
Hi 👋 , I try to reproduce this issue and in order to make zombienet works you should add the `cumulus_based` flag to the parachain

```toml
[settings]
timeout = 1000

[relaychain]
default_image = "chocnet/polkadot-debug:latest"
default_command = "/home/gitpod/relay/polkadot/target/release/polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

[[parachains]]
id = 2000
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  image = "chocnet/parachain-collator:latest"
  command = "./target/debug/parachain-collator"
  args = ["-lparachain=debug"]
```

And also, the `parachain-collator` command is not output the `RPC` log that zombienet use to check if the node is up. I think that issue is related to the branch version you are using `polkadot-v0.9.24`. Is possible to bump to `polkadot-v0.9.28`?

Thanks!!
